apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lattix-frontier.fullname" . }}-federation
data:
  enabled: {{ .Values.federation.enabled | quote }}
  clusterName: {{ .Values.federation.clusterName | quote }}
  region: {{ .Values.federation.region | quote }}
  peers: {{ join "," .Values.federation.peers | quote }}
