apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lattix-frontier.fullname" . }}-jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lattix-jaeger
  template:
    metadata:
      labels:
        app: lattix-jaeger
    spec:
      securityContext:
{{ toYaml .Values.security.podSecurityContext | indent 8 }}
      containers:
        - name: jaeger
          image: {{ include "lattix-frontier.imageRef" .Values.vendorImages.jaeger }}
          securityContext:
{{ toYaml .Values.security.containerSecurityContext | indent 12 }}
