{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lattix-control-plane-default-deny
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - lattix-api
          - lattix-orchestrator
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lattix-api-ingress-allow
spec:
  podSelector:
    matchLabels:
      app: lattix-api
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: lattix-envoy
        - podSelector:
            matchLabels:
              app: lattix-orchestrator
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lattix-api-egress-allow
spec:
  podSelector:
    matchLabels:
      app: lattix-api
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app: lattix-vault
        - podSelector:
            matchLabels:
              app: lattix-opa
        - podSelector:
            matchLabels:
              app: lattix-nats
        - podSelector:
            matchLabels:
              app: lattix-postgres
        - podSelector:
            matchLabels:
              app: lattix-jaeger
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lattix-orchestrator-egress-allow
spec:
  podSelector:
    matchLabels:
      app: lattix-orchestrator
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - podSelector:
            matchLabels:
              app: lattix-api
        - podSelector:
            matchLabels:
              app: lattix-vault
        - podSelector:
            matchLabels:
              app: lattix-opa
        - podSelector:
            matchLabels:
              app: lattix-nats
        - podSelector:
            matchLabels:
              app: lattix-postgres
        - podSelector:
            matchLabels:
              app: lattix-jaeger
  policyTypes:
    - Egress
{{- end }}
