http_port 3128

acl sandbox_clients src 172.16.0.0/12
acl sandbox_clients src 192.168.0.0/16
acl sandbox_clients src 10.0.0.0/8
acl CONNECT method CONNECT

http_access allow sandbox_clients
http_access deny all

cache deny all
access_log stdio:/var/log/squid/access.log
cache_log stdio:/var/log/squid/cache.log
coredump_dir /var/spool/squid
