from __future__ import annotations

from typing import Any


INTEGRATION_STARTER_TEMPLATE_SEEDS: list[dict[str, Any]] = [
    {
        "id": "github",
        "wave": 1,
        "name": "GitHub",
        "summary": "Repository read, PR review, and issue automation.",
        "type": "http",
        "base_url": "https://api.github.com",
        "auth_type": "bearer",
        "secret_ref": "secret/integrations/github/token",
        "metadata_json": {
            "auth": {"method": "bearer", "prefix": "Bearer"},
            "template_id": "github",
            "template_wave": 1,
        },
        "capabilities": ["/repo-read", "/code-search", "/issue-triage", "/pr-review", "scm"],
        "permission_scopes": ["repo:read", "pull_requests:write", "issues:write"],
        "data_access": ["source-code-metadata", "issue-data", "pull-request-data"],
        "egress_allowlist": ["api.github.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "slack",
        "wave": 1,
        "name": "Slack",
        "summary": "Notifications, approvals, and chatops flows.",
        "type": "http",
        "base_url": "https://slack.com/api",
        "auth_type": "bearer",
        "secret_ref": "secret/integrations/slack/token",
        "metadata_json": {
            "auth": {"method": "bearer", "prefix": "Bearer"},
            "template_id": "slack",
            "template_wave": 1,
        },
        "capabilities": ["/chatops", "/notify", "/approval-request", "/incident-room"],
        "permission_scopes": ["chat:write", "channels:read", "users:read"],
        "data_access": ["channel-metadata", "message-write"],
        "egress_allowlist": ["slack.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "jira-cloud",
        "wave": 1,
        "name": "Jira Cloud",
        "summary": "Ticketing and incident workflow automation.",
        "type": "http",
        "base_url": "https://your-domain.atlassian.net/rest/api/3",
        "auth_type": "basic",
        "secret_ref": "secret/integrations/jira/token",
        "metadata_json": {
            "auth": {"method": "basic", "username": "email@example.com"},
            "template_id": "jira-cloud",
            "template_wave": 1,
        },
        "capabilities": ["/ticket-read", "/ticket-write", "/incident-triage", "/work-item-sync"],
        "permission_scopes": ["read:jira-work", "write:jira-work"],
        "data_access": ["issue-data", "project-metadata"],
        "egress_allowlist": ["atlassian.net"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "confluence-cloud",
        "wave": 1,
        "name": "Confluence Cloud",
        "summary": "Runbooks and wiki search for retrieval flows.",
        "type": "http",
        "base_url": "https://your-domain.atlassian.net/wiki/api/v2",
        "auth_type": "basic",
        "secret_ref": "secret/integrations/confluence/token",
        "metadata_json": {
            "auth": {"method": "basic", "username": "email@example.com"},
            "template_id": "confluence-cloud",
            "template_wave": 1,
        },
        "capabilities": ["/wiki-search", "/runbook-read", "/kb-search"],
        "permission_scopes": ["read:confluence-content", "search:confluence"],
        "data_access": ["knowledge-base", "document-metadata"],
        "egress_allowlist": ["atlassian.net"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "notion",
        "wave": 1,
        "name": "Notion",
        "summary": "Workspace docs and internal knowledge access.",
        "type": "http",
        "base_url": "https://api.notion.com/v1",
        "auth_type": "bearer",
        "secret_ref": "secret/integrations/notion/token",
        "metadata_json": {
            "auth": {"method": "bearer", "prefix": "Bearer"},
            "template_id": "notion",
            "template_wave": 1,
        },
        "capabilities": ["/docs-search", "/workspace-knowledge", "/notes-read"],
        "permission_scopes": ["content:read"],
        "data_access": ["knowledge-base", "page-metadata"],
        "egress_allowlist": ["api.notion.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "pagerduty",
        "wave": 1,
        "name": "PagerDuty",
        "summary": "On-call, incidents, and service alerting.",
        "type": "http",
        "base_url": "https://api.pagerduty.com",
        "auth_type": "bearer",
        "secret_ref": "secret/integrations/pagerduty/token",
        "metadata_json": {
            "auth": {"method": "bearer", "prefix": "Token token="},
            "template_id": "pagerduty",
            "template_wave": 1,
        },
        "capabilities": ["/oncall", "/incident-page", "/service-alerting", "/incident-triage"],
        "permission_scopes": ["incidents:read", "incidents:write", "schedules:read"],
        "data_access": ["incident-data", "oncall-roster"],
        "egress_allowlist": ["api.pagerduty.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "postgresql",
        "wave": 1,
        "name": "PostgreSQL",
        "summary": "Internal analytics and relational lookup access.",
        "type": "database",
        "base_url": "postgresql://db-host:5432/database",
        "auth_type": "basic",
        "secret_ref": "secret/integrations/postgres/password",
        "metadata_json": {
            "auth": {"method": "basic", "username": "service_user"},
            "template_id": "postgresql",
            "template_wave": 1,
        },
        "capabilities": ["/sql-read", "/analytics", "/customer-lookup", "/reporting"],
        "permission_scopes": ["read-only"],
        "data_access": ["relational-data", "analytics"],
        "egress_allowlist": ["db-host"],
        "publisher": "custom",
        "execution_mode": "local",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "qdrant",
        "wave": 1,
        "name": "Qdrant",
        "summary": "Self-hosted vector retrieval with API key auth.",
        "type": "vector",
        "base_url": "https://your-qdrant-host:6333",
        "auth_type": "api_key",
        "secret_ref": "secret/integrations/qdrant/api-key",
        "metadata_json": {
            "auth": {"method": "api_key", "location": "header", "key_name": "api-key"},
            "template_id": "qdrant",
            "template_wave": 1,
        },
        "capabilities": ["/retrieval", "/semantic-search", "/vector-query"],
        "permission_scopes": ["collections:read", "points:read"],
        "data_access": ["embeddings", "vector-index"],
        "egress_allowlist": ["your-qdrant-host"],
        "publisher": "custom",
        "execution_mode": "local",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "linear",
        "wave": 2,
        "name": "Linear",
        "summary": "Product planning and issue sync for engineering teams.",
        "type": "http",
        "base_url": "https://api.linear.app/graphql",
        "auth_type": "bearer",
        "secret_ref": "secret/integrations/linear/token",
        "metadata_json": {
            "auth": {"method": "bearer", "prefix": "Bearer"},
            "template_id": "linear",
            "template_wave": 2,
        },
        "capabilities": ["/planning", "/issue-sync", "/roadmap-read"],
        "permission_scopes": ["issues:read", "issues:write"],
        "data_access": ["issue-data", "roadmap-data"],
        "egress_allowlist": ["api.linear.app"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "datadog",
        "wave": 2,
        "name": "Datadog",
        "summary": "Metrics, logs, traces, and alert context.",
        "type": "http",
        "base_url": "https://api.datadoghq.com/api/v1",
        "auth_type": "api_key",
        "secret_ref": "secret/integrations/datadog/api-key",
        "metadata_json": {
            "auth": {"method": "api_key", "location": "header", "key_name": "DD-API-KEY"},
            "template_id": "datadog",
            "template_wave": 2,
            "note": "Some Datadog endpoints also require an app key.",
        },
        "capabilities": ["/metrics", "/logs", "/traces", "/alerts"],
        "permission_scopes": ["metrics:read", "monitors:read"],
        "data_access": ["observability-metadata", "alert-data"],
        "egress_allowlist": ["api.datadoghq.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "zendesk",
        "wave": 2,
        "name": "Zendesk",
        "summary": "Support tickets and customer case routing.",
        "type": "http",
        "base_url": "https://your-subdomain.zendesk.com/api/v2",
        "auth_type": "basic",
        "secret_ref": "secret/integrations/zendesk/token",
        "metadata_json": {
            "auth": {"method": "basic", "username": "email@example.com/token"},
            "template_id": "zendesk",
            "template_wave": 2,
        },
        "capabilities": ["/support", "/ticket-triage", "/customer-case-read"],
        "permission_scopes": ["tickets:read", "tickets:write"],
        "data_access": ["support-ticket-data", "customer-case-data"],
        "egress_allowlist": ["zendesk.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "hubspot",
        "wave": 2,
        "name": "HubSpot",
        "summary": "CRM contacts and deal lookup workflows.",
        "type": "http",
        "base_url": "https://api.hubapi.com",
        "auth_type": "bearer",
        "secret_ref": "secret/integrations/hubspot/token",
        "metadata_json": {
            "auth": {"method": "bearer", "prefix": "Bearer"},
            "template_id": "hubspot",
            "template_wave": 2,
        },
        "capabilities": ["/crm", "/contacts", "/deal-lookup"],
        "permission_scopes": ["crm.objects.contacts.read", "crm.objects.deals.read"],
        "data_access": ["contact-data", "deal-data"],
        "egress_allowlist": ["api.hubapi.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "snowflake",
        "wave": 2,
        "name": "Snowflake",
        "summary": "Warehouse analytics via service credentials.",
        "type": "database",
        "base_url": "https://account.snowflakecomputing.com",
        "auth_type": "basic",
        "secret_ref": "secret/integrations/snowflake/password",
        "metadata_json": {
            "auth": {"method": "basic", "username": "service_user"},
            "template_id": "snowflake",
            "template_wave": 2,
            "note": "Confirm runtime adapter support before enabling in production.",
        },
        "capabilities": ["/warehouse", "/analytics", "/business-metrics"],
        "permission_scopes": ["read-only"],
        "data_access": ["warehouse-data", "analytics"],
        "egress_allowlist": ["snowflakecomputing.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "servicenow",
        "wave": 2,
        "name": "ServiceNow",
        "summary": "ITSM incidents and change request automation.",
        "type": "http",
        "base_url": "https://your-instance.service-now.com/api/now",
        "auth_type": "basic",
        "secret_ref": "secret/integrations/servicenow/password",
        "metadata_json": {
            "auth": {"method": "basic", "username": "service_account"},
            "template_id": "servicenow",
            "template_wave": 2,
        },
        "capabilities": ["/itsm", "/change-request", "/incident-management"],
        "permission_scopes": ["incident:read", "incident:write", "change_request:read"],
        "data_access": ["incident-data", "change-data"],
        "egress_allowlist": ["service-now.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "pinecone",
        "wave": 2,
        "name": "Pinecone",
        "summary": "Hosted vector index retrieval.",
        "type": "vector",
        "base_url": "https://your-index-host.pinecone.io",
        "auth_type": "api_key",
        "secret_ref": "secret/integrations/pinecone/api-key",
        "metadata_json": {
            "auth": {"method": "api_key", "location": "header", "key_name": "Api-Key"},
            "template_id": "pinecone",
            "template_wave": 2,
        },
        "capabilities": ["/retrieval", "/semantic-search", "/vector-query"],
        "permission_scopes": ["indexes:read", "query:read"],
        "data_access": ["embeddings", "vector-index"],
        "egress_allowlist": ["pinecone.io"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "microsoft-graph",
        "wave": 3,
        "name": "Microsoft Graph",
        "summary": "Mail, calendar, users, files, and Teams automation with delegated OAuth.",
        "type": "http",
        "base_url": "https://graph.microsoft.com/v1.0",
        "auth_type": "oauth2",
        "secret_ref": "secret/integrations/microsoft/client-secret",
        "metadata_json": {
            "auth": {
                "method": "oauth2",
                "provider": "microsoft",
                "grant_type": "authorization_code",
                "authorize_url": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
                "token_url": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
                "client_id": "frontier-microsoft-client",
                "scopes": ["User.Read", "Mail.ReadWrite", "offline_access"],
                "tenant": "common",
                "audience": "https://graph.microsoft.com",
                "redirect_path": "/builder/integrations?oauth_panel=1",
                "client_secret_ref": "secret/integrations/microsoft/client-secret",
                "token_secret_ref": "secret/integrations/microsoft/access-token",
                "refresh_token_secret_ref": "secret/integrations/microsoft/refresh-token",
                "account_label": "Shared mailbox",
            },
            "template_id": "microsoft-graph",
            "template_wave": 3,
        },
        "capabilities": ["/mail", "/calendar", "/directory-read", "/sharepoint-search"],
        "permission_scopes": ["User.Read", "Mail.ReadWrite", "offline_access"],
        "data_access": [
            "mailbox-data",
            "calendar-data",
            "directory-metadata",
            "sharepoint-documents",
        ],
        "egress_allowlist": ["graph.microsoft.com", "login.microsoftonline.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "google-workspace",
        "wave": 3,
        "name": "Google Workspace",
        "summary": "Gmail, Drive, Calendar, and Workspace data automation with OAuth.",
        "type": "http",
        "base_url": "https://www.googleapis.com",
        "auth_type": "oauth2",
        "secret_ref": "secret/integrations/google/client-secret",
        "metadata_json": {
            "auth": {
                "method": "oauth2",
                "provider": "google",
                "grant_type": "authorization_code",
                "authorize_url": "https://accounts.google.com/o/oauth2/v2/auth",
                "token_url": "https://oauth2.googleapis.com/token",
                "client_id": "frontier-google-client",
                "scopes": [
                    "openid",
                    "email",
                    "profile",
                    "https://www.googleapis.com/auth/drive.readonly",
                    "https://www.googleapis.com/auth/gmail.modify",
                ],
                "audience": "https://www.googleapis.com",
                "redirect_path": "/builder/integrations?oauth_panel=1",
                "client_secret_ref": "secret/integrations/google/client-secret",
                "token_secret_ref": "secret/integrations/google/access-token",
                "refresh_token_secret_ref": "secret/integrations/google/refresh-token",
                "account_label": "Workspace operations",
            },
            "template_id": "google-workspace",
            "template_wave": 3,
        },
        "capabilities": ["/gmail", "/drive", "/calendar", "/workspace-search"],
        "permission_scopes": [
            "openid",
            "email",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/gmail.modify",
        ],
        "data_access": ["mailbox-data", "drive-documents", "calendar-events", "workspace-metadata"],
        "egress_allowlist": ["accounts.google.com", "oauth2.googleapis.com", "www.googleapis.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
    {
        "id": "salesforce",
        "wave": 3,
        "name": "Salesforce",
        "summary": "Accounts, opportunities, and cases through OAuth-backed CRM access.",
        "type": "http",
        "base_url": "https://your-instance.my.salesforce.com/services/data/v61.0",
        "auth_type": "oauth2",
        "secret_ref": "secret/integrations/salesforce/client-secret",
        "metadata_json": {
            "auth": {
                "method": "oauth2",
                "provider": "salesforce",
                "grant_type": "authorization_code",
                "authorize_url": "https://login.salesforce.com/services/oauth2/authorize",
                "token_url": "https://login.salesforce.com/services/oauth2/token",
                "client_id": "frontier-salesforce-client",
                "scopes": ["api", "refresh_token", "offline_access"],
                "audience": "https://login.salesforce.com",
                "redirect_path": "/builder/integrations?oauth_panel=1",
                "client_secret_ref": "secret/integrations/salesforce/client-secret",
                "token_secret_ref": "secret/integrations/salesforce/access-token",
                "refresh_token_secret_ref": "secret/integrations/salesforce/refresh-token",
                "account_label": "Revenue operations",
            },
            "template_id": "salesforce",
            "template_wave": 3,
        },
        "capabilities": ["/crm", "/opportunity-read", "/case-read", "/account-lookup"],
        "permission_scopes": ["api", "refresh_token", "offline_access"],
        "data_access": ["contact-data", "account-data", "opportunity-data", "case-data"],
        "egress_allowlist": ["login.salesforce.com", "my.salesforce.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
        "signature_verified": False,
        "approved_for_marketplace": False,
    },
]
