from __future__ import annotations

from typing import Any


MCP_STARTER_TEMPLATE_SEEDS: list[dict[str, Any]] = [
    {
        "id": "github",
        "wave": 1,
        "name": "GitHub",
        "summary": "Repository read, pull request review, and issue automation over a staged MCP connection.",
        "transport": "streamable_http",
        "auth_type": "bearer",
        "secret_ref": "secret/integrations/mcp/github/token",
        "capabilities": ["/repo-read", "/code-search", "/issue-triage", "/pr-review"],
        "permission_scopes": ["repo:read", "pull_requests:write", "issues:write"],
        "data_access": ["source-code-metadata", "issue-data", "pull-request-data"],
        "egress_allowlist": ["github.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "slack",
        "wave": 1,
        "name": "Slack",
        "summary": "Notifications, approvals, and chatops workflows exposed through MCP.",
        "transport": "streamable_http",
        "auth_type": "bearer",
        "secret_ref": "secret/integrations/mcp/slack/token",
        "capabilities": ["/chatops", "/notify", "/approval-request", "/incident-room"],
        "permission_scopes": ["chat:write", "channels:read", "users:read"],
        "data_access": ["channel-metadata", "message-write"],
        "egress_allowlist": ["slack.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "jira-cloud",
        "wave": 1,
        "name": "Jira Cloud",
        "summary": "Ticketing and incident automation through a staged Jira MCP endpoint.",
        "transport": "streamable_http",
        "auth_type": "basic",
        "secret_ref": "secret/integrations/mcp/jira/token",
        "capabilities": ["/ticket-read", "/ticket-write", "/incident-triage", "/work-item-sync"],
        "permission_scopes": ["read:jira-work", "write:jira-work"],
        "data_access": ["issue-data", "project-metadata"],
        "egress_allowlist": ["atlassian.net"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "confluence-cloud",
        "wave": 1,
        "name": "Confluence Cloud",
        "summary": "Runbook and wiki retrieval workflows over an approved MCP connection.",
        "transport": "streamable_http",
        "auth_type": "basic",
        "secret_ref": "secret/integrations/mcp/confluence/token",
        "capabilities": ["/wiki-search", "/runbook-read", "/kb-search"],
        "permission_scopes": ["read:confluence-content", "search:confluence"],
        "data_access": ["knowledge-base", "document-metadata"],
        "egress_allowlist": ["atlassian.net"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "notion",
        "wave": 1,
        "name": "Notion",
        "summary": "Workspace knowledge access through a staged Notion MCP connection.",
        "transport": "streamable_http",
        "auth_type": "bearer",
        "secret_ref": "secret/integrations/mcp/notion/token",
        "capabilities": ["/docs-search", "/workspace-knowledge", "/notes-read"],
        "permission_scopes": ["content:read"],
        "data_access": ["knowledge-base", "page-metadata"],
        "egress_allowlist": ["api.notion.com", "mcp.notion.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "pagerduty",
        "wave": 1,
        "name": "PagerDuty",
        "summary": "On-call and incident workflows exposed through MCP.",
        "transport": "streamable_http",
        "auth_type": "bearer",
        "secret_ref": "secret/integrations/mcp/pagerduty/token",
        "capabilities": ["/oncall", "/incident-page", "/service-alerting", "/incident-triage"],
        "permission_scopes": ["incidents:read", "incidents:write", "schedules:read"],
        "data_access": ["incident-data", "oncall-roster"],
        "egress_allowlist": ["pagerduty.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "postgresql",
        "wave": 1,
        "name": "PostgreSQL",
        "summary": "Local or private MCP front-end for read-only relational queries.",
        "transport": "streamable_http",
        "auth_type": "basic",
        "secret_ref": "secret/integrations/mcp/postgres/password",
        "capabilities": ["/sql-read", "/analytics", "/customer-lookup", "/reporting"],
        "permission_scopes": ["read-only"],
        "data_access": ["relational-data", "analytics"],
        "egress_allowlist": ["localhost", "postgres"],
        "publisher": "custom",
        "execution_mode": "local",
    },
    {
        "id": "qdrant",
        "wave": 1,
        "name": "Qdrant",
        "summary": "Private vector retrieval exposed via an approved MCP endpoint.",
        "transport": "streamable_http",
        "auth_type": "api_key",
        "secret_ref": "secret/integrations/mcp/qdrant/api-key",
        "capabilities": ["/retrieval", "/semantic-search", "/vector-query"],
        "permission_scopes": ["collections:read", "points:read"],
        "data_access": ["embeddings", "vector-index"],
        "egress_allowlist": ["localhost", "qdrant"],
        "publisher": "custom",
        "execution_mode": "local",
    },
    {
        "id": "linear",
        "wave": 2,
        "name": "Linear",
        "summary": "Planning and issue sync workflows over a staged MCP connection.",
        "transport": "streamable_http",
        "auth_type": "bearer",
        "secret_ref": "secret/integrations/mcp/linear/token",
        "capabilities": ["/planning", "/issue-sync", "/roadmap-read"],
        "permission_scopes": ["issues:read", "issues:write"],
        "data_access": ["issue-data", "roadmap-data"],
        "egress_allowlist": ["linear.app"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "datadog",
        "wave": 2,
        "name": "Datadog",
        "summary": "Metrics, logs, traces, and alerts through an approved MCP endpoint.",
        "transport": "streamable_http",
        "auth_type": "api_key",
        "secret_ref": "secret/integrations/mcp/datadog/api-key",
        "capabilities": ["/metrics", "/logs", "/traces", "/alerts"],
        "permission_scopes": ["metrics:read", "monitors:read"],
        "data_access": ["observability-metadata", "alert-data"],
        "egress_allowlist": ["datadoghq.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "zendesk",
        "wave": 2,
        "name": "Zendesk",
        "summary": "Support ticket routing and customer case read access over MCP.",
        "transport": "streamable_http",
        "auth_type": "basic",
        "secret_ref": "secret/integrations/mcp/zendesk/token",
        "capabilities": ["/support", "/ticket-triage", "/customer-case-read"],
        "permission_scopes": ["tickets:read", "tickets:write"],
        "data_access": ["support-ticket-data", "customer-case-data"],
        "egress_allowlist": ["zendesk.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "hubspot",
        "wave": 2,
        "name": "HubSpot",
        "summary": "CRM contacts and deal lookups surfaced through MCP.",
        "transport": "streamable_http",
        "auth_type": "bearer",
        "secret_ref": "secret/integrations/mcp/hubspot/token",
        "capabilities": ["/crm", "/contacts", "/deal-lookup"],
        "permission_scopes": ["crm.objects.contacts.read", "crm.objects.deals.read"],
        "data_access": ["contact-data", "deal-data"],
        "egress_allowlist": ["hubapi.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "snowflake",
        "wave": 2,
        "name": "Snowflake",
        "summary": "Warehouse analytics through a staged Snowflake MCP gateway.",
        "transport": "streamable_http",
        "auth_type": "basic",
        "secret_ref": "secret/integrations/mcp/snowflake/password",
        "capabilities": ["/warehouse", "/analytics", "/business-metrics"],
        "permission_scopes": ["read-only"],
        "data_access": ["warehouse-data", "analytics"],
        "egress_allowlist": ["snowflakecomputing.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "servicenow",
        "wave": 2,
        "name": "ServiceNow",
        "summary": "ITSM incident and change workflows exposed through MCP.",
        "transport": "streamable_http",
        "auth_type": "basic",
        "secret_ref": "secret/integrations/mcp/servicenow/password",
        "capabilities": ["/itsm", "/change-request", "/incident-management"],
        "permission_scopes": ["incident:read", "incident:write", "change_request:read"],
        "data_access": ["incident-data", "change-data"],
        "egress_allowlist": ["service-now.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "pinecone",
        "wave": 2,
        "name": "Pinecone",
        "summary": "Hosted vector retrieval through a staged MCP endpoint.",
        "transport": "streamable_http",
        "auth_type": "api_key",
        "secret_ref": "secret/integrations/mcp/pinecone/api-key",
        "capabilities": ["/retrieval", "/semantic-search", "/vector-query"],
        "permission_scopes": ["indexes:read", "query:read"],
        "data_access": ["embeddings", "vector-index"],
        "egress_allowlist": ["pinecone.io"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "microsoft-graph",
        "wave": 3,
        "name": "Microsoft Graph",
        "summary": "Mail, calendar, directory, and file workflows backed by provider-aware OAuth.",
        "transport": "streamable_http",
        "auth_type": "oauth2",
        "secret_ref": "secret/integrations/mcp/microsoft/client-secret",
        "capabilities": ["/mail", "/calendar", "/directory-read", "/sharepoint-search"],
        "permission_scopes": ["User.Read", "Mail.ReadWrite", "offline_access"],
        "data_access": [
            "mailbox-data",
            "calendar-data",
            "directory-metadata",
            "sharepoint-documents",
        ],
        "egress_allowlist": ["graph.microsoft.com", "login.microsoftonline.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "google-workspace",
        "wave": 3,
        "name": "Google Workspace",
        "summary": "Workspace mail, drive, calendar, and directory workflows backed by OAuth.",
        "transport": "streamable_http",
        "auth_type": "oauth2",
        "secret_ref": "secret/integrations/mcp/google/client-secret",
        "capabilities": ["/gmail", "/drive", "/calendar", "/workspace-search"],
        "permission_scopes": ["openid", "email", "https://www.googleapis.com/auth/drive.readonly"],
        "data_access": ["mailbox-data", "drive-documents", "calendar-events", "workspace-metadata"],
        "egress_allowlist": ["accounts.google.com", "oauth2.googleapis.com", "googleapis.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
    {
        "id": "salesforce",
        "wave": 3,
        "name": "Salesforce",
        "summary": "Accounts, opportunities, and case workflows exposed through OAuth-backed MCP access.",
        "transport": "streamable_http",
        "auth_type": "oauth2",
        "secret_ref": "secret/integrations/mcp/salesforce/client-secret",
        "capabilities": ["/crm", "/opportunity-read", "/case-read", "/account-lookup"],
        "permission_scopes": ["api", "refresh_token", "offline_access"],
        "data_access": ["contact-data", "account-data", "opportunity-data", "case-data"],
        "egress_allowlist": ["login.salesforce.com", "salesforce.com"],
        "publisher": "third_party",
        "execution_mode": "sandboxed",
    },
]
